update search component
LBCamden/lbcamden-frontend pull request #181
Opened 2024-05-13 11:40 UTC by oluoluoxenfree

2024-05-13 13:58 UTC, chrisdevereux commented on src/lbcamden/components/search/template.njk
> +  action="/{{ action }}"
I'd leave the slash off here - I think users would expect to specify the exact action url

2024-05-13 13:59 UTC, chrisdevereux commented on src/lbcamden/components/search/template.njk
> +  {% set method = 'post' %}
Maybe just let people specify `method` as a string? method="get", method="post", etc. Defaulting to get is right, though.

2024-05-15 09:42 UTC, alexwybraniec requested changes
All looks good, just needs a little bit of refactoring.

2024-05-15 09:42 UTC, alexwybraniec commented on src/lbcamden/components/search/search.yaml
> +  - name: postMethod
@oluoluoxenfree As discussed can you update this, and resubmit for review

2024-05-15 09:42 UTC, alexwybraniec commented on src/lbcamden/components/search/search.yaml
> +    type: string
@oluoluoxenfree Need to change this type to "object" instead of "string"

2024-05-15 09:42 UTC, alexwybraniec commented on src/lbcamden/components/search/search.yaml
> +    hidden: true
@oluoluoxenfree As discussed we think these examples should not be "hidden", so please remove this and add descriptions for the examples

2024-05-15 09:42 UTC, alexwybraniec commented on src/lbcamden/components/search/search.yaml
> +    hidden: true
Also applies to the examples below.

2024-05-15 09:42 UTC, alexwybraniec commented on src/lbcamden/components/search/template.njk
> +  {% set action = params.action %}
@oluoluoxenfree As discussed can you tweak the indentation of these if statements to bring the conditional tags inline with each other.

2024-05-15 09:42 UTC, alexwybraniec commented on src/lbcamden/components/search/template.njk
@oluoluoxenfree As discussed, let's use the `| default()` nunjucks filter on some of these attributes, and remove the nunjucks conditionals above. See the usage of `params.labelText | default('Search Camden.gov.uk')` as an example.

2024-05-15 14:33 UTC, alexwybraniec approved these changes

2024-05-15 14:33 UTC, merged